In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving rainfall in india 1901-2015.csv to rainfall in india 1901-2015.csv


# Exploratory Data Analysis

In [3]:
dataset = pd.read_csv('rainfall in india 1901-2015.csv')

In [4]:
dataset.dropna(how='any', inplace=True)

In [5]:
X = dataset.iloc[:,[0,1,-1,-2,-3,-4]].values
Y = dataset.iloc[:,-5].values

In [6]:
print(X)

[['ANDAMAN & NICOBAR ISLANDS' 1901 980.3 1696.3 560.3 136.3]
 ['ANDAMAN & NICOBAR ISLANDS' 1902 716.7 2185.9 458.3 159.8]
 ['ANDAMAN & NICOBAR ISLANDS' 1903 690.6 1874.0 236.1 156.7]
 ...
 ['LAKSHADWEEP' 2013 177.6 1057.0 131.1 60.6]
 ['LAKSHADWEEP' 2014 290.5 958.5 76.7 69.3]
 ['LAKSHADWEEP' 2015 555.4 860.9 223.9 2.7]]


In [7]:
Y = Y.reshape(-1,1)

In [8]:
print(Y)

[[3373.2]
 [3520.7]
 [2957.4]
 ...
 [1426.3]
 [1395. ]
 [1642.9]]


# Dealing with invalid dataset

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [10]:
print(X)

[['ANDAMAN & NICOBAR ISLANDS' 1901 980.3 1696.3 560.3 136.3]
 ['ANDAMAN & NICOBAR ISLANDS' 1902 716.7 2185.9 458.3 159.8]
 ['ANDAMAN & NICOBAR ISLANDS' 1903 690.6 1874.0 236.1 156.7]
 ...
 ['LAKSHADWEEP' 2013 177.6 1057.0 131.1 60.6]
 ['LAKSHADWEEP' 2014 290.5 958.5 76.7 69.3]
 ['LAKSHADWEEP' 2015 555.4 860.9 223.9 2.7]]


In [11]:
print(Y)

[[3373.2]
 [3520.7]
 [2957.4]
 ...
 [1426.3]
 [1395. ]
 [1642.9]]


# Encoding dataset

In [12]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])

In [13]:
print(X)

[[0 1901 980.3 1696.3 560.3 136.3]
 [0 1902 716.7 2185.9 458.3 159.8]
 [0 1903 690.6 1874.0 236.1 156.7]
 ...
 [18 2013 177.6 1057.0 131.1 60.6]
 [18 2014 290.5 958.5 76.7 69.3]
 [18 2015 555.4 860.9 223.9 2.7]]


In [14]:

print(Y)

[[3373.2]
 [3520.7]
 [2957.4]
 ...
 [1426.3]
 [1395. ]
 [1642.9]]


# Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [16]:
print(X)

[[-1.70794392 -1.72941497  4.96963041  0.89812848  2.02437445  1.6208145 ]
 [-1.70794392 -1.69924441  3.38543641  1.59172697  1.51511613  2.01825062]
 [-1.70794392 -1.66907385  3.22857957  1.1498696   0.40573183  1.96582288]
 ...
 [ 0.03462896  1.64968797  0.1455313  -0.00754455 -0.11850467  0.34056283]
 [ 0.03462896  1.67985853  0.82404232 -0.14708591 -0.39010911  0.48769876]
 [ 0.03462896  1.71002909  2.41604911 -0.28535228  0.34482054 -0.63865212]]


In [17]:
print(Y)

[[3373.2]
 [3520.7]
 [2957.4]
 ...
 [1426.3]
 [1395. ]
 [1642.9]]


# Splitting Dataset into Training and Testing data

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [19]:
print(X_train)

[[ 0.22824817 -0.73378643 -0.34306874 -0.42659363 -0.70714738 -0.58284194]
 [-0.64303827  0.26184212 -0.78899892 -0.26707732 -0.55986188 -0.68431499]
 [ 1.29315382 -0.49242193 -0.54499939  0.41051287 -0.24432143  2.54252805]
 ...
 [-0.44941906  0.62388886 -0.49692066 -0.95146749  0.59695334  4.1390374 ]
 [-0.06218064  1.71002909 -0.20784733  1.19902782 -0.51492732 -0.63865212]
 [ 0.22824817 -1.45787991 -0.29078313 -0.05245278 -0.75308048 -0.68431499]]


In [20]:
print(Y_train)

[[ 876.6]
 [ 938.7]
 [1711.4]
 ...
 [1021. ]
 [2082. ]
 [1134.4]]


# Training the model

In [21]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [22]:
regressor.score(X_train,Y_train)

1.0

In [23]:
y_pred = np.array(regressor.predict(X_test),dtype=int)
Y_test = np.array(Y_test,dtype=int)

In [24]:
print(y_pred)

[1100  755 4300 1106 2308 2887 1114  859 3953  967 3111 2651 1171 2604
  446  244 1027  551  984 2719  928  938  516 1368  765  769 1447  324
 1115  816 1572 4173 2295 1560 2876 1140 1206  473 1332 2583 2498  904
 2660  625 1189  717 1467 1634 2320 1113  818 3123  891  930  292 1416
  786 3079 1215  726  533 3163 2594 1353 2580 1101 1849  381  793 1101
  748 2701 1396 1608 1350 1948  635  778 1440  362 2648 1227 1100 3084
  935 1502 1308 1664 2876 1406 2521  875 1206  591 2807 1435  865 1178
 2403 2854  890  551 1310  644 3349 1511 1207  901  583  348  762 1350
  780 1053 1448  590  481  783  703 1178  744 3385  419  578 2372  751
 1769 1427  425 4017 1488 1475 3588 1017  983 1564  705 2869 3842 2237
 1333 1692  900 1427 1609 1041  777 2524  719 1035  922 1524 3326 2789
 2534  204  860 2802 2533  990 1396 3908 2221 2869  848 1164 2661 2807
 2358 3341 3216  998  900 1085 1187 2242  897 1495  179 1521 3370 1563
  967 3007 1061 1252 1182 1357  740 1678 3385 1872  992  527 2752 2422
 1586 

In [25]:
print(Y_test)

[[1224]
 [ 740]
 [4090]
 [1078]
 [2314]
 [2971]
 [1088]
 [ 641]
 [4041]
 [ 835]
 [3255]
 [2547]
 [1111]
 [2638]
 [ 451]
 [ 264]
 [1003]
 [ 543]
 [1003]
 [2931]
 [ 926]
 [ 941]
 [ 565]
 [1467]
 [ 640]
 [ 858]
 [1455]
 [ 302]
 [1111]
 [ 783]
 [1586]
 [4138]
 [2175]
 [1862]
 [2820]
 [1182]
 [1064]
 [ 551]
 [1281]
 [2537]
 [2550]
 [ 955]
 [2591]
 [ 626]
 [1060]
 [ 736]
 [1443]
 [1600]
 [2361]
 [1053]
 [ 790]
 [3327]
 [ 936]
 [1051]
 [ 265]
 [1446]
 [ 805]
 [3027]
 [1175]
 [ 723]
 [ 553]
 [3591]
 [2632]
 [1382]
 [2634]
 [1099]
 [1812]
 [ 368]
 [ 828]
 [1093]
 [ 739]
 [2699]
 [1441]
 [1534]
 [1349]
 [1859]
 [ 580]
 [ 808]
 [1368]
 [ 347]
 [2522]
 [1093]
 [1061]
 [3150]
 [ 943]
 [1532]
 [1283]
 [1615]
 [2860]
 [1306]
 [2663]
 [1069]
 [1225]
 [ 549]
 [2906]
 [1477]
 [ 847]
 [1372]
 [2507]
 [2917]
 [ 878]
 [ 568]
 [1240]
 [ 657]
 [2782]
 [1535]
 [1253]
 [ 914]
 [ 567]
 [ 663]
 [ 755]
 [1397]
 [ 758]
 [1082]
 [1504]
 [ 581]
 [ 484]
 [ 784]
 [ 695]
 [1198]
 [ 688]
 [3047]
 [ 440]
 [ 590]
 [2427]


In [26]:
y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [27]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Actual Rainfall','Predicted Rainfall'])

In [28]:
print(dataframe)

     Actual Rainfall  Predicted Rainfall
0               1224                1100
1                740                 755
2               4090                4300
3               1078                1106
4               2314                2308
..               ...                 ...
813             1705                1591
814              428                 425
815             2920                2766
816              775                 731
817             1286                1308

[818 rows x 2 columns]


# Calculating Accuracy

In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.004889975550122249