In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving rainfall in india 1901-2015.csv to rainfall in india 1901-2015.csv


# Exploratory Data Analysis

In [ ]:
dataset = pd.read_csv('rainfall in india 1901-2015.csv')

In [ ]:
dataset.dropna(how='any', inplace=True)

In [ ]:
X = dataset.iloc[:,[0,1,-1,-2,-3,-4]].values
Y = dataset.iloc[:,-5].values

In [ ]:
print(X)

[['ANDAMAN & NICOBAR ISLANDS' 1901 980.3 1696.3 560.3 136.3]
 ['ANDAMAN & NICOBAR ISLANDS' 1902 716.7 2185.9 458.3 159.8]
 ['ANDAMAN & NICOBAR ISLANDS' 1903 690.6 1874.0 236.1 156.7]
 ...
 ['LAKSHADWEEP' 2013 177.6 1057.0 131.1 60.6]
 ['LAKSHADWEEP' 2014 290.5 958.5 76.7 69.3]
 ['LAKSHADWEEP' 2015 555.4 860.9 223.9 2.7]]


In [ ]:
Y = Y.reshape(-1,1)

In [ ]:
print(Y)

[[3373.2]
 [3520.7]
 [2957.4]
 ...
 [1426.3]
 [1395. ]
 [1642.9]]


# Dealing with invalid dataset

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [ ]:
print(X)

[['ANDAMAN & NICOBAR ISLANDS' 1901 980.3 1696.3 560.3 136.3]
 ['ANDAMAN & NICOBAR ISLANDS' 1902 716.7 2185.9 458.3 159.8]
 ['ANDAMAN & NICOBAR ISLANDS' 1903 690.6 1874.0 236.1 156.7]
 ...
 ['LAKSHADWEEP' 2013 177.6 1057.0 131.1 60.6]
 ['LAKSHADWEEP' 2014 290.5 958.5 76.7 69.3]
 ['LAKSHADWEEP' 2015 555.4 860.9 223.9 2.7]]


In [ ]:
print(Y)

[[3373.2]
 [3520.7]
 [2957.4]
 ...
 [1426.3]
 [1395. ]
 [1642.9]]


# Encoding dataset

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])

In [ ]:
print(X)

[[0 1901 980.3 1696.3 560.3 136.3]
 [0 1902 716.7 2185.9 458.3 159.8]
 [0 1903 690.6 1874.0 236.1 156.7]
 ...
 [18 2013 177.6 1057.0 131.1 60.6]
 [18 2014 290.5 958.5 76.7 69.3]
 [18 2015 555.4 860.9 223.9 2.7]]


In [ ]:

print(Y)

[[3373.2]
 [3520.7]
 [2957.4]
 ...
 [1426.3]
 [1395. ]
 [1642.9]]


# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [ ]:
print(X)

[[-1.70794392 -1.72941497  4.96963041  0.89812848  2.02437445  1.6208145 ]
 [-1.70794392 -1.69924441  3.38543641  1.59172697  1.51511613  2.01825062]
 [-1.70794392 -1.66907385  3.22857957  1.1498696   0.40573183  1.96582288]
 ...
 [ 0.03462896  1.64968797  0.1455313  -0.00754455 -0.11850467  0.34056283]
 [ 0.03462896  1.67985853  0.82404232 -0.14708591 -0.39010911  0.48769876]
 [ 0.03462896  1.71002909  2.41604911 -0.28535228  0.34482054 -0.63865212]]


In [ ]:
print(Y)

[[3373.2]
 [3520.7]
 [2957.4]
 ...
 [1426.3]
 [1395. ]
 [1642.9]]


# Splitting Dataset into Training and Testing data

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
print(X_train)

[[ 0.22824817 -0.73378643 -0.34306874 -0.42659363 -0.70714738 -0.58284194]
 [-0.64303827  0.26184212 -0.78899892 -0.26707732 -0.55986188 -0.68431499]
 [ 1.29315382 -0.49242193 -0.54499939  0.41051287 -0.24432143  2.54252805]
 ...
 [-0.44941906  0.62388886 -0.49692066 -0.95146749  0.59695334  4.1390374 ]
 [-0.06218064  1.71002909 -0.20784733  1.19902782 -0.51492732 -0.63865212]
 [ 0.22824817 -1.45787991 -0.29078313 -0.05245278 -0.75308048 -0.68431499]]


In [ ]:
print(Y_train)

[[ 876.6]
 [ 938.7]
 [1711.4]
 ...
 [1021. ]
 [2082. ]
 [1134.4]]


# Training the model

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
regressor.score(X_train,Y_train)

0.9999999948233315

In [ ]:
y_pred = np.array(regressor.predict(X_test),dtype=int)
Y_test = np.array(Y_test,dtype=int)

In [ ]:
print(y_pred)

[[1224]
 [ 740]
 [4090]
 [1078]
 [2314]
 [2971]
 [1088]
 [ 641]
 [4041]
 [ 834]
 [3255]
 [2546]
 [1111]
 [2638]
 [ 451]
 [ 264]
 [1003]
 [ 543]
 [1003]
 [2931]
 [ 926]
 [ 941]
 [ 566]
 [1467]
 [ 640]
 [ 858]
 [1455]
 [ 302]
 [1110]
 [ 783]
 [1586]
 [4137]
 [2174]
 [1862]
 [2820]
 [1182]
 [1064]
 [ 551]
 [1281]
 [2537]
 [2550]
 [ 955]
 [2591]
 [ 626]
 [1060]
 [ 736]
 [1442]
 [1600]
 [2361]
 [1053]
 [ 790]
 [3327]
 [ 936]
 [1050]
 [ 265]
 [1446]
 [ 805]
 [3027]
 [1176]
 [ 723]
 [ 553]
 [3591]
 [2632]
 [1382]
 [2634]
 [1099]
 [1813]
 [ 368]
 [ 828]
 [1093]
 [ 739]
 [2699]
 [1441]
 [1534]
 [1349]
 [1858]
 [ 581]
 [ 808]
 [1368]
 [ 347]
 [2522]
 [1093]
 [1061]
 [3150]
 [ 943]
 [1532]
 [1283]
 [1615]
 [2860]
 [1306]
 [2663]
 [1069]
 [1225]
 [ 549]
 [2906]
 [1477]
 [ 847]
 [1372]
 [2507]
 [2917]
 [ 878]
 [ 568]
 [1240]
 [ 657]
 [2782]
 [1535]
 [1253]
 [ 914]
 [ 567]
 [ 663]
 [ 755]
 [1397]
 [ 758]
 [1082]
 [1504]
 [ 581]
 [ 484]
 [ 784]
 [ 695]
 [1198]
 [ 688]
 [3047]
 [ 440]
 [ 590]
 [2427]


In [ ]:
print(Y_test)

[[1224]
 [ 740]
 [4090]
 [1078]
 [2314]
 [2971]
 [1088]
 [ 641]
 [4041]
 [ 835]
 [3255]
 [2547]
 [1111]
 [2638]
 [ 451]
 [ 264]
 [1003]
 [ 543]
 [1003]
 [2931]
 [ 926]
 [ 941]
 [ 565]
 [1467]
 [ 640]
 [ 858]
 [1455]
 [ 302]
 [1111]
 [ 783]
 [1586]
 [4138]
 [2175]
 [1862]
 [2820]
 [1182]
 [1064]
 [ 551]
 [1281]
 [2537]
 [2550]
 [ 955]
 [2591]
 [ 626]
 [1060]
 [ 736]
 [1443]
 [1600]
 [2361]
 [1053]
 [ 790]
 [3327]
 [ 936]
 [1051]
 [ 265]
 [1446]
 [ 805]
 [3027]
 [1175]
 [ 723]
 [ 553]
 [3591]
 [2632]
 [1382]
 [2634]
 [1099]
 [1812]
 [ 368]
 [ 828]
 [1093]
 [ 739]
 [2699]
 [1441]
 [1534]
 [1349]
 [1859]
 [ 580]
 [ 808]
 [1368]
 [ 347]
 [2522]
 [1093]
 [1061]
 [3150]
 [ 943]
 [1532]
 [1283]
 [1615]
 [2860]
 [1306]
 [2663]
 [1069]
 [1225]
 [ 549]
 [2906]
 [1477]
 [ 847]
 [1372]
 [2507]
 [2917]
 [ 878]
 [ 568]
 [1240]
 [ 657]
 [2782]
 [1535]
 [1253]
 [ 914]
 [ 567]
 [ 663]
 [ 755]
 [1397]
 [ 758]
 [1082]
 [1504]
 [ 581]
 [ 484]
 [ 784]
 [ 695]
 [1198]
 [ 688]
 [3047]
 [ 440]
 [ 590]
 [2427]


In [ ]:
y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [ ]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Actual Rainfall','Predicted Rainfall'])

In [ ]:
print(dataframe)

     Actual Rainfall  Predicted Rainfall
0               1224                1224
1                740                 740
2               4090                4090
3               1078                1078
4               2314                2314
..               ...                 ...
813             1705                1705
814              428                 428
815             2920                2920
816              775                 775
817             1286                1286

[818 rows x 2 columns]


# Calculating Accuracy

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.9290953545232273